{
 "title": "GoShimmer Local Metrics",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Worker Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "workerpools_load", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Syncing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Message Request Queue Size",
   "type": "graph",
   "description": "Number of messages currently requested by the message tangle.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_request_queue_size",
     "legendFormat": "Message Request Queue Size"
    }
   ]
  },
  {
   "title": "Messages in Database",
   "type": "graph",
   "description": "Describes the amount of total, solid and not solid messages in the node's database.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tangle_message_solid_count_db", "legendFormat": "Solid Messages in DB" },
    {
     "expr": "tangle_message_total_count_db - tangle_message_solid_count_db",
     "legendFormat": "Not Solid Messages in DB"
    },
    { "expr": "tangle_message_total_count_db", "legendFormat": "Total Messages in DB" }
   ]
  },
  {
   "title": "Average Solidification Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "tangle_message_avg_solidification_time",
     "legendFormat": "Avg Solidification Time"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GoShimmer",
   "type": "stat",
   "description": "Version number of node software.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_info_app" }
   ]
  },
  {
   "title": "Synced",
   "type": "stat",
   "description": "Describes if the node is in synced state.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync" }
   ]
  },
  {
   "title": "Total MPS",
   "type": "stat",
   "description": "Aggregated MPS for all message types in the communication layer.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(tangle_message_total_count[5m])",
     "legendFormat": "Total MPS"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Current CPU usage of the node.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "stat",
   "description": "Memory consumed by the node.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_mem_usage_bytes/1024/1024"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size of the ledger database.",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_size_bytes/1024/1024" }
   ]
  },
  {
   "title": "MPS, Autopeering, Traffic, Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Message Per Second Per Type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "MPS" }
   ],
   "targets": [
    {
     "expr": "irate(tangle_messages_per_type_count{message_type=\"data\"}[5m])",
     "legendFormat": "Data Message Per Second"
    },
    {
     "expr": "irate(tangle_messages_per_type_count{message_type=\"value\"}[5m])",
     "legendFormat": "Transaction Per Second"
    },
    {
     "expr": "irate(tangle_messages_per_type_count{message_type=\"drng\"}[5m])",
     "legendFormat": "dRNG Messages Per Second"
    },
    {
     "expr": "irate(tangle_messages_per_type_count{message_type=\"faucet\"}[5m])",
     "legendFormat": "Faucet Messages Per Second"
    },
    {
     "expr": "irate(tangle_messages_per_type_count{message_type=\"netowrkdelay\"}[5m])",
     "legendFormat": "Network Delay Messages Per Second"
    }
   ]
  },
  {
   "title": "Autopeering Neighbor Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Distance" }
   ],
   "targets": [
    { "expr": "autopeering_avg_distance", "legendFormat": "Average" },
    { "expr": "autopeering_max_distance", "legendFormat": "Max" },
    { "expr": "autopeering_min_distance", "legendFormat": "Min" }
   ]
  },
  {
   "title": "Current Neighbors",
   "type": "stat",
   "description": "Number of currently connected neighbors.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_neighbor_connections_count - autopeering_neighbor_drop_count"
    }
   ]
  },
  {
   "title": "AvgNeighbor Connection Lifetime",
   "type": "stat",
   "description": "Calculated for each dropped neighbor.",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_avg_neighbor_connection_lifetime"
    }
   ]
  },
  {
   "title": "New Neighbor Connections",
   "type": "stat",
   "description": "Amount of newly registered neighbor connections.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_neighbor_connections_count"
    }
   ]
  },
  {
   "title": "Dropped Neighbor Connections",
   "type": "stat",
   "description": "Amount of neighbor connections dropped.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "autopeering_neighbor_drop_count"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "graph",
   "description": "Shows tips in message and value layer.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tangle_message_tips_count", "legendFormat": "Message Layer Tips" },
    { "expr": "tangle_value_tips", "legendFormat": "Value Layer Tips" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "process_mem_usage_bytes/1024/1024",
     "legendFormat": "Memory Consumption"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(traffic_analysis_outbound_bytes[1m])",
     "legendFormat": "Analysis TX"
    },
    {
     "expr": "irate(traffic_autopeering_inbound_bytes[1m])",
     "legendFormat": "Autopeering RX"
    },
    {
     "expr": "irate(traffic_autopeering_outbound_bytes[1m])",
     "legendFormat": "Autopeering TX"
    },
    {
     "expr": "irate(traffic_fpc_inbound_bytes[1m])",
     "legendFormat": "FPC RX"
    },
    {
     "expr": "irate(traffic_fpc_outbound_bytes[1m])",
     "legendFormat": "FPC TX"
    },
    {
     "expr": "irate(traffic_gossip_inbound_bytes[1m])",
     "legendFormat": "Gossip RX"
    },
    {
     "expr": "irate(traffic_gossip_outbound_bytes[1m])",
     "legendFormat": "Gossip Tx"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 50 },
   "content": "\n# Total Network Traffic\n\n\nSince the start of the node.\n"
  },
  {
   "title": "Gossip TX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traffic_gossip_outbound_bytes" }
   ]
  },
  {
   "title": "Gossip RX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traffic_gossip_inbound_bytes" }
   ]
  },
  {
   "title": "Analysis",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_analysis_outbound_bytes"
    }
   ]
  },
  {
   "title": "Autopeering TX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_autopeering_outbound_bytes"
    }
   ]
  },
  {
   "title": "Autopeering RX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic_autopeering_inbound_bytes"
    }
   ]
  },
  {
   "title": "FPC RX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traffic_fpc_inbound_bytes" }
   ]
  },
  {
   "title": "FPC TX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traffic_fpc_outbound_bytes" }
   ]
  },
  { "title": "FPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Active Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fpc_active_conflicts", "legendFormat": "Active Conflicts" }
   ]
  },
  {
   "title": "Average Rounds To Finalize",
   "type": "stat",
   "description": "The average number of rounds it takes to finalize a conflict.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fpc_avg_rounds_to_finalize" }
   ]
  },
  {
   "title": "Finalized Conflicts",
   "type": "stat",
   "description": "Number of finalized conflicts.",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fpc_finalized_conflicts" }
   ]
  },
  {
   "title": "Failed Conflicts",
   "type": "stat",
   "description": "Number of failed conflicts.",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fpc_failed_conflicts" }
   ]
  },
  {
   "title": "FPC Queries RX",
   "type": "graph",
   "description": "Describes how many FPC query requests the node has received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none", "label": "Queries Per Second" }
   ],
   "targets": [
    {
     "expr": "irate(fpc_queries_received[5m])",
     "legendFormat": "FPC Queries RX"
    }
   ]
  },
  {
   "title": "FPC Queries TX Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "none", "label": "Queries Per Second" }
   ],
   "targets": [
    {
     "expr": "irate(fpc_query_replies_not_received[5m])",
     "legendFormat": "FPC Queries TX Failed"
    }
   ]
  },
  {
   "title": "FPC Conflict Queries RX",
   "type": "graph",
   "description": "Describes how many FPC opinions were requested from the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none", "label": "Conflict Queries Per Second" }
   ],
   "targets": [
    {
     "expr": "irate(fpc_queries_opinion_received[5m])",
     "legendFormat": "FPC Conflict Queries RX"
    }
   ]
  },
  {
   "title": "FPC Conflict Queries TX Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "none", "label": "Conflict Queries Per Second" }
   ],
   "targets": [
    {
     "expr": "irate(fpc_query_opinion_replies_not_received[5m])",
     "legendFormat": "FPC Conflict Queries TX Failed"
    },
    {}
   ]
  }
 ]
}